### ISSUE TITLE
Underline only problematic chunk

### ISSUE THREAD

**Issue by omfgnuts** [zerok/remark-lint-write-good#2]
Hi!

I configured remark-lint-write-good for Atom successfully, but it underlines whole sentence instead of just the problematic part of it.

Is there any option that allows doing that? Or the issue is not in the plugin itself?

**Comment by zerok** [comment]
I haven’t tried it with Atom yet 🙂 I will try to find some time for it this weekend 🙂

**Comment by zerok** [comment]
OK, it looks like either an issue in remark-lint-write-good or something lowerlevel. I will try to further debug it :)

**Comment by omfgnuts** [comment]
Thank you for looking into that :)

**Comment by zerok** [comment]
Found the issue :) It should be fixed with v1.0.2 😄
