### ISSUE TITLE
Seems to have issues with FrontMatter

### ISSUE THREAD

**Issue by rjhilgefort** [zerok/remark-lint-write-good#4]
It complains like this on every file. Any way to get around the error?

![image](https://user-images.githubusercontent.com/2034823/47270614-a7c7cf80-d52b-11e8-9ead-1d2cb4fd47d1.png)

```md
---
path: "/20181019"
date: "2018-10-19"
title: "Friday, October 19, 2018"
tags: []
excerpt: "A preview of 2018-10-19"
---
```

**Comment by zerok** [comment]
Hm... if I create a test for your file, I don't get any errors. What versions of remark, nlcst-to-string etc. are you using?

**Comment by rjhilgefort** [comment]
here's everything I'm using:

```json
  "dependencies": {
    "gatsby": "^2.0.0",
    "gatsby-plugin-sharp": "^2.0.7",
    "gatsby-plugin-typography": "^2.2.0",
    "gatsby-remark-emojis": "^0.2.3",
    "gatsby-remark-external-links": "^0.0.4",
    "gatsby-remark-images": "^2.0.4",
    "gatsby-remark-prismjs": "^3.0.2",
    "gatsby-remark-smartypants": "^2.0.5",
    "gatsby-source-filesystem": "^2.0.1-rc.6",
    "gatsby-transformer-remark": "^2.1.1-rc.5",
    "prismjs": "^1.15.0",
    "ramda": "^0.25.0",
    "react": "^16.5.1",
    "react-dom": "^16.5.1",
    "react-typography": "^0.16.13",
    "recompose": "^0.30.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.83.0",
    "styled-components": "^4.0.2",
    "typography": "^0.16.17",
    "typography-theme-funston": "^0.15.10",
    "typography-theme-github": "^0.15.10"
  },
  "devDependencies": {
    "npm-run-all": "^4.1.3",
    "onchange": "^5.0.2",
    "prettier-standard": "^8.0.1",
    "remark-cli": "^5.0.0",
    "remark-frontmatter": "^1.3.0",
    "remark-lint": "^6.0.2",
    "remark-lint-write-good": "^1.0.3",
    "remark-preset-lint-consistent": "^2.0.2",
    "remark-preset-lint-markdown-style-guide": "^2.1.2",
    "remark-preset-lint-recommended": "^3.0.2",
    "remark-validate-links": "^7.1.0",
    "treis": "^2.6.0"
  }
```

**Comment by zerok** [comment]
I've also tried it now with nlcst-to-string 2.0.2 still without any error :/ Can you perhaps please share your remark call? It sounds like remark-lint-write-good is clashing with some other item in your processing chain 🙂

**Comment by rjhilgefort** [comment]
Thanks for trying it out. Here's my remark call:

```json
  "scripts": {
    "lint:md": "remark .",
  },
```

and here's what my `.remarkrc.js` looks like:

```js
module.exports = {
  "plugins": [
    "remark-preset-lint-recommended",
    "remark-preset-lint-markdown-style-guide",
    "remark-preset-lint-consistent",
    "remark-validate-links",
    "remark-frontmatter",
    ["remark-lint-write-good", ["warn", {
      "passive": false,
      "adverb": false,
    }]],
    ["remark-lint-maximum-line-length", false],
    ["remark-lint-table-pipe-alignment", false],
  ]
}
```

**Comment by rjhilgefort** [comment]
I went through and tried turning off each plugin individually to see if there was some interaction- but the error persisted for each one. I then tried turning all plugins off except `write-good` and the problem persisted.

![image](https://user-images.githubusercontent.com/2034823/47518510-647da180-d848-11e8-9b27-e3368926e266.png)

**Comment by zerok** [comment]
Thank you :) I'll continue trying out setups tomorrow :)

**Comment by zerok** [comment]
I've pushed a workaround for this in v1.0.4 🙂  I hope this fixes the issue for you 😄

**Comment by rjhilgefort** [comment]
Thanks for trying to find a fix! I installed `v1.0.4`, but the problem persists.

![image](https://user-images.githubusercontent.com/2034823/47605643-61a8bb00-d9c6-11e8-8038-a1f07e8a4571.png)

If you're out of ideas, I can try to get familiar with the code and see if I can track it down. Thanks again for looking into this.

**Comment by zerok** [comment]
Can you please try pinning the version to “1.0.4” instead of “^1.0.4”? “1.0.3” also matches “^1.0.4” and the stacktrace looks like 1.0.3 🙂

**Comment by rjhilgefort** [comment]
Oh 💩 ! My fault. I upgraded to 1.0.4 for real this time and re-ran things. Problem seems to still be there. 🙁 

![image](https://user-images.githubusercontent.com/2034823/47608833-5d45c780-d9f1-11e8-8f87-5e158466b400.png)

**Comment by zerok** [comment]
More ifs then 😂

**Comment by zerok** [comment]
I've now wrapped the node-serialization into a try-catch-clause and released it as 1.0.5. Can you please try it again? 😄

**Comment by rjhilgefort** [comment]
👍 That does it! I don't want to know about my write good errors in my front matter anyhow. Thanks for your help with this!

![image](https://user-images.githubusercontent.com/2034823/47622257-a9177000-dac8-11e8-975a-543d5e5c1e96.png)

**Comment by zerok** [comment]
Thanks for helping with debugging this 😄
